// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2x9EQi6xKB4v_VjXAwky3oAdWSykEB54',
    appId: '1:783352570656:web:3541add008e3f671bf6d45',
    messagingSenderId: '783352570656',
    projectId: 'dua-app-e1b3b',
    authDomain: 'dua-app-e1b3b.firebaseapp.com',
    storageBucket: 'dua-app-e1b3b.firebasestorage.app',
    measurementId: 'G-ZK4B9XPBJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKkVt7Odg98sMwfjkR8iHUPvlQXGYQvs',
    appId: '1:783352570656:android:695ac2fbf6a1ecc3bf6d45',
    messagingSenderId: '783352570656',
    projectId: 'dua-app-e1b3b',
    storageBucket: 'dua-app-e1b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqTdV6I9JUZ0mqKBr4ZSIHky8ZkY2gNM',
    appId: '1:783352570656:ios:bbff089e15e6b2febf6d45',
    messagingSenderId: '783352570656',
    projectId: 'dua-app-e1b3b',
    storageBucket: 'dua-app-e1b3b.firebasestorage.app',
    iosBundleId: 'com.example.myDuaApp',
  );

}